# Usa la imagen base de NGINX
FROM nginx:latest

# Copia el archivo HTML estático al directorio de trabajo de NGINX
COPY index.html /usr/share/nginx/html

# Exponer el puerto 80 para que NGINX pueda ser accesible desde fuera del contenedor
EXPOSE 80
